#pragma once

#include <core/bad.h>

typedef struct {
    R_RW u32 CR;
    R_RW u32 HSISCR;
    R_RW u32 CRRCR;
    R_RW u32 CSICFGR;
    R_RW u32 CFGR;
    u32 __reserved00;
    R_RW u32 D1CFGR;
    R_RW u32 D2CFGR;
    R_RW u32 D3CFGR;
    u32 __reserved1;

    R_RW u32 PLLCKSELR;
    R_RW u32 PLLCFGR;
    R_RW u32 PLL1DIVR;
    R_RW u32 PLL1FRACR;
    R_RW u32 PLL2DIVR;
    R_RW u32 PLL2FRACR;
    R_RW u32 PLL3DIVR;
    R_RW u32 PLL3FRACR;
    u32 __reserved2;

    R_RW u32 D1CCIPR;
    R_RW u32 D2CCIP1R;
    R_RW u32 D2CCIP2R;
    R_RW u32 D3CCIPR;
    u32 __reserved3;

    R_RW u32 CIER;
    R_RW u32 CIFR;
    R_RW u32 CICR;
    u32 __reserved4;

    R_RW u32 BDCR;
    R_RW u32 CSR;
    u32 __reserved5;

    R_RW u32 AHB3RSTR;
    R_RW u32 AHB1RSTR;
    R_RW u32 AHB2RSTR;
    R_RW u32 AHB4RSTR;

    R_RW u32 APB3RSTR;
    R_RW u32 APB1LRSTR;
    R_RW u32 APB1HRSTR;
    R_RW u32 APB2RSTR;
    R_RW u32 APB4RSTR;

    R_RW u32 GCR;
    u32 __reserved6;

    R_RW u32 D3AMR;
    u32 __reserved7[9];

    R_RW u32 RSR;

    R_RW u32 AHB3ENR;
    R_RW u32 AHB1ENR;
    R_RW u32 AHB2ENR;
    R_RW u32 AHB4ENR;

    R_RW u32 APB3ENR;
    R_RW u32 APB1LENR;
    R_RW u32 APB1HENR;
    R_RW u32 APB2ENR;
    R_RW u32 APB4ENR;
    u32 __reserved8;

    R_RW u32 AHB3LPENR;
    R_RW u32 AHB1LPENR;
    R_RW u32 AHB2LPENR;
    R_RW u32 AHB4LPENR;
    R_RW u32 APB3LPENR;
    R_RW u32 APB1LLPENR;
    R_RW u32 APB1HLPENR;
    R_RW u32 APB2LPENR;
    R_RW u32 APB4LPENR;
    u32 __reserved9[5];

    R_RW u32 C1_AHB3ENR;
    R_RW u32 C1_AHB1ENR;
    R_RW u32 C1_AHB2ENR;
    R_RW u32 C1_AHB4ENR;
    R_RW u32 C1_APB3ENR;
    R_RW u32 C1_APB1LENR;
    R_RW u32 C1_APB1HENR;
    R_RW u32 C1_APB2ENR;
    R_RW u32 C1_APB4ENR;
    u32 __reservedA;

    R_RW u32 C1_AHB3LPENR;
    R_RW u32 C1_AHB1LPENR;
    R_RW u32 C1_AHB2LPENR;
    R_RW u32 C1_AHB4LPENR;
    R_RW u32 C1_APB3LPENR;
    R_RW u32 C1_APB1LLPENR;
    R_RW u32 C1_APB1HLPENR;
    R_RW u32 C1_APB2LPENR;
    R_RW u32 C1_APB4LPENR;

    u32 __reservedB[31];
} RCC_t;

#define RCC_D3CCIPR_ADCSEL_Msk ((0x3ul) << 16ul)
#define RCC_D3CCIPR_ADCSEL_per_ck ((0x2ul) << 16ul)
#define RCC_AHB1ENR_ADC12EN (1ul << 5ul)

#define RCC_APB1LENR_USART3EN (1UL << 18)

#define RCC_AHB2ENR_SRAM1EN (1UL << 29)
#define RCC_AHB2ENR_SRAM2EN (1UL << 30)
#define RCC_AHB2ENR_SRAM3EN (1UL << 31)

#define RCC_APB3ENR_LTDCEN (1UL << 3)

#define RCC_AHB3ENR_MDMAEN (1UL << 0)
#define RCC_AHB3ENR_DMA2DEN (1UL << 4)
#define RCC_AHB3ENR_JPGDECEN (1UL << 5)
#define RCC_AHB3ENR_FMCEN (1UL << 12)
#define RCC_AHB3ENR_QSPIEN (1UL << 14)
#define RCC_AHB3ENR_SDMMC1EN (1UL << 16)

#define RCC_AHB3RSTR_MDMARST (1UL << 0)
#define RCC_AHB3RSTR_DMA2DRST (1UL << 4)
#define RCC_AHB3RSTR_JPGDECRST (1UL << 5)
#define RCC_AHB3RSTR_FMCRST (1UL << 12)
#define RCC_AHB3RSTR_QSPIRST (1UL << 14)
#define RCC_AHB3RSTR_SDMMC1RST (1UL << 16)

#define RCC_APB4ENR_SYSCFGEN (1ul << 1)

#define RCC_AHB4ENR_GPIOAEN (1UL << 0)
#define RCC_AHB4ENR_GPIOBEN (1UL << 1)
#define RCC_AHB4ENR_GPIOCEN (1UL << 2)
#define RCC_AHB4ENR_GPIODEN (1UL << 3)
#define RCC_AHB4ENR_GPIOEEN (1UL << 4)
#define RCC_AHB4ENR_GPIOFEN (1UL << 5)
#define RCC_AHB4ENR_GPIOGEN (1UL << 6)
#define RCC_AHB4ENR_GPIOHEN (1UL << 7)
#define RCC_AHB4ENR_GPIOIEN (1UL << 8)
#define RCC_AHB4ENR_GPIOJEN (1UL << 9)
#define RCC_AHB4ENR_GPIOKEN (1UL << 10)
#define RCC_AHB4ENR_GPIOxEN_Mask 0x7ff

#define RCC_DxCFGR_DxPPRE1_Mask (0x7UL << 4)
#define RCC_DxCFGR_DxPPRE1_DIV2 (1UL << 6)

#define RCC_DxCFGR_DxPPRE2_Mask (0x7UL << 8)
#define RCC_DxCFGR_DxPPRE2_DIV2 (1UL << 10)

#define RCC_D1CFGR_HPRE_Mask (0x7UL)
#define RCC_D1CFGR_HPRE_DIV2 (1UL << 3)

#define RCC_D1CFGR_D1CPRE_Mask (0xFUL << 8)
#define RCC_D1CFGR_D1CPRE_DIV1 0UL

#define RCC_CFGR_SW_Mask 0x7UL
#define RCC_CFGR_SW_PLL1 0x3UL

#define RCC_CFGR_SWS_Mask (0x7UL << 3)
#define RCC_CFGR_SWS_PLL1 (0x3UL << 3)

#define RCC_CR_HSION 1UL
#define RCC_CR_CSION (1UL << 7)
#define RCC_CR_HSEON (1UL << 16)
#define RCC_CR_PLL1ON (1UL << 24)
#define RCC_CR_PLL2ON (1UL << 26)
#define RCC_CR_PLL3ON (1UL << 28)
#define RCC_CR_HSI48ON (1UL << 12)
#define RCC_CSR_LSION 1UL

#define RCC_CR_HSIRDY (1UL << 2)
#define RCC_CR_CSIRDY (1UL << 8)
#define RCC_CR_HSERDY (1UL << 17)

#define RCC_CR_PLL1RDY (1UL << 25)
#define RCC_CR_PLL2RDY (1UL << 27)
#define RCC_CR_PLL3RDY (1UL << 29)

#define RCC_CR_HSI48RDY (1UL << 13)
#define RCC_CSR_LSIRDY (1UL << 1)

#define RCC_PLLSOURCE_HSE (0x2UL)
#define RCC_PLLSOURCE_Mask (0x3UL)

#define RCC_PLLSOURCE_DIVM1_Pos 4UL
#define RCC_PLLSOURCE_DIVM2_Pos 12UL
#define RCC_PLLSOURCE_DIVM3_Pos 20UL
#define RCC_PLLSOURCE_DIVM1_Mask (0x3FUL << 4)
#define RCC_PLLSOURCE_DIVM2_Mask (0x3FUL << 12)
#define RCC_PLLSOURCE_DIVM3_Mask (0x3FUL << 20)

#define RCC_PLLxDIVR_DIVR_Pos 24UL
#define RCC_PLLxDIVR_DIVQ_Pos 16UL
#define RCC_PLLxDIVR_DIVP_Pos 9UL
#define RCC_PLLxDIVR_DIVN_Pos 0UL

// these masks are unshifted
#define RCC_PLLxDIVR_DIVR_UMask (0x7FUL)
#define RCC_PLLxDIVR_DIVQ_UMask (0x7FUL)
#define RCC_PLLxDIVR_DIVP_UMask (0x7FUL)
#define RCC_PLLxDIVR_DIVN_UMask (0x1FFUL)

#define RCC_PLLCFGR_PLL1FRACEN (1UL)
#define RCC_PLLCFGR_DIVP1EN (1UL << 16)
#define RCC_PLLCFGR_DIVQ1EN (1UL << 17)
#define RCC_PLLCFGR_DIVR1EN (1UL << 18)

#define RCC_PLLCFGR_PLL1VCOSEL_Mask (1UL << 1)
#define RCC_PLLCFGR_PLL1RGE_Pos 2UL
#define RCC_PLLCFGR_PLL1RGE_Mask (0x3UL << 2)

#define RCC_PLL1FRACR_FRACN1_Pos 3UL
#define RCC_PLL1FRACR_FRACN1_Mask (0xfffUL << 3)

#define RCC_D2CCIP2R_USART234578SEL_Mask 0x7UL
#define RCC_D2CCIP2R_USART234578SEL_Pos 0UL
#define RCC_D2CCIP2R_USART234578SEL_HSI 0x3UL

#define RCC_APB1LRSTR_USART3RST (1UL << 18)

#define RCC_D1CCIPR_FMCSEL_Pos 0
#define RCC_D1CCIPR_FMCSEL_Msk (0x3ul << RCC_D1CCIPR_FMCSEL_Pos)
#define RCC_D1CCIPR_FMCSEL_HCLK3 (0x0ul << RCC_D1CCIPR_FMCSEL_Pos)
#define RCC_D1CCIPR_FMCSEL_PLL1Q (0x1ul << RCC_D1CCIPR_FMCSEL_Pos)
#define RCC_D1CCIPR_FMCSEL_PLL2R (0x2ul << RCC_D1CCIPR_FMCSEL_Pos)
#define RCC_D1CCIPR_FMCSEL_PERCK (0x3ul << RCC_D1CCIPR_FMCSEL_Pos)

#define RCC_D1CCIPR_QSPISEL_Pos 4
#define RCC_D1CCIPR_QSPISEL_Msk (0x3ul << RCC_D1CCIPR_QSPISEL_Pos)
#define RCC_D1CCIPR_QSPISEL_HCLK3 (0x0ul << RCC_D1CCIPR_QSPISEL_Pos)
#define RCC_D1CCIPR_QSPISEL_PLL1Q (0x1ul << RCC_D1CCIPR_QSPISEL_Pos)
#define RCC_D1CCIPR_QSPISEL_PLL2R (0x2ul << RCC_D1CCIPR_QSPISEL_Pos)
#define RCC_D1CCIPR_QSPISEL_PERCK (0x3ul << RCC_D1CCIPR_QSPISEL_Pos)

#define RCC_D1CCIPR_SDMMCSEL_Pos 16
#define RCC_D1CCIPR_SDMMCSEL_Msk (0x1ul << RCC_D1CCIPR_SDMMCSEL_Pos)
#define RCC_D1CCIPR_SDMMCSEL_PLL1Q (0x0ul << RCC_D1CCIPR_SDMMCSEL_Pos)
#define RCC_D1CCIPR_SDMMCSEL_PLL2R (0x1ul << RCC_D1CCIPR_SDMMCSEL_Pos)

#define RCC_D1CCIPR_CKPERSEL_Pos 28
#define RCC_D1CCIPR_CKPERSEL_Msk (0x3ul << RCC_D1CCIPR_CKPERSEL_Pos)
#define RCC_D1CCIPR_CKPERSEL_HSI (0x0ul << RCC_D1CCIPR_CKPERSEL_Pos)
#define RCC_D1CCIPR_CKPERSEL_CSI (0x1ul << RCC_D1CCIPR_CKPERSEL_Pos)
#define RCC_D1CCIPR_CKPERSEL_HSE (0x2ul << RCC_D1CCIPR_CKPERSEL_Pos)
#define RCC_D1CCIPR_CKPERSEL_DIS (0x3ul << RCC_D1CCIPR_CKPERSEL_Pos)